# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Use CentOS machine image
  config.vm.box = "centos/stream8"

  if Vagrant.has_plugin?("vagrant-vbguest") then
	config.vbguest.auto_update = false
  end

  config.vm.define "eparisotS"
  config.vm.hostname = "eparisotS"

  # Kubernetes API Access
  config.vm.network "forwarded_port", guest: 6443, host: 6443

  # Expose NodePort ports
  config.vm.network "forwarded_port", guest: 80, host: 80, protocol: "tcp"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.42.110"

  config.vm.boot_timeout 1000

  # Define the resources for the virtualbox
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
    vb.name = "eparisotS"
  end

  # Run some setup script to install K3s on he VM
  config.vm.provision "k3s shell script", type: "shell",
      path: "k3s.sh"
end