Vagrant.configure("2") do |config|
  config.vm.box = "mehdee/k3s_one"
  config.vm.box_version = "0.1.1"
  config.vagrant.plugins = "vagrant-vbguest"
  config.vbguest.auto_update = false
  config.vm.synced_folder ".", "/vagrant/"
  config.vm.provider "virtualbox" do |v|
	v.memory = 1024
	v.cpus = 1
	v.linked_clone = true
  end

  config.vm.define "msabwatS" do |node|
    node.vm.hostname = "msabwatS"
    node.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "msabwatSW" do |node|
    node.vm.hostname = "msabwatSW"
    node.vm.network "private_network", ip: "192.168.56.111"
  end
  config.vm.provision "k3s shell script", type: "shell", path: "scripts/k3s.sh"

end
